apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: itm
  namespace: {{ .Values.global.namespace }}
spec:
  to:
    kind: Service
    name: itmsvc
  path: /get_all_streams
  port:
    targetPort: 8000
