apiVersion: v1
kind: Service
metadata:
  name: itmsvc
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "itm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "itm.selectorLabels" . | nindent 4 }}
