apiVersion: v1
kind: Service
metadata:
  name: itm_svc
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "itm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  selector:
    {{- include "itm.selectorLabels" . | nindent 4 }}
