apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: grafana
  namespace: {{ .Values.global.namespace }}
spec:
  to:
    kind: Service
    name: grafana
  path: /
  port:
    targetPort: 3000
